---
namespace: ansi_colle
name: linux_config
version: 1.0.0
readme: README.md
authors:
  - Chun Pan Yung

description: collection of roles that will share across repo.

license:
  - GPL-2.0-or-later
repository: https://gitlab.com/ahhh-tomation/ansi_colle
