---
- name: Include task list if OS family is Debian
  ansible.builtin.include_tasks: _ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Create directory
  become: false
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/Repos/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0750'
