---
- name: Create directory
  become: false
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/Repos/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0750'
